### PR TITLE
Build Docker image in CI

### PR DESCRIPTION
**Pull request by dbrgn**
Might be of interest to you, @TimWolla.

### CODE REVIEW

**Comment by TimWolla** [comment]
Oh sweet, that would save me from needing to rebuild the image manually. Thanks for the ping!

**Comment by dbrgn** [comment]
I'd like to add some env vars to the image for configuration, but probably not today. Maybe later this week.

**Comment by TimWolla** [comment]
What are you thinking about? Personally I haven't missed anything.

I simply start the container via: `/usr/bin/docker run --rm --name sekursranko --network *snip* -v /srv/sekursranko/tank:/sekursranko sekursranko` and off I go.

**Comment by dbrgn** [comment]
Ideally every relevant option in the configfile should be configurable through env vars as well (e.g. max backup size).

I created #25 for tracking this.

**Pull request merged**
